## Bônus

### É Possível Criar Gráfico Interativo com Python no Power BI?

In [1]:
# Imports
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
# Importa o dataset
dataset = pd.read_csv('dadosRH_modificado.csv')

In [2]:
# Dadoos
dataset.head()

,id_funcionario,departmento,regiao,educacao,genero,canal_recrutamento,numero_treinamentos,idade,aval_ano_anterior,tempo_servico,promovido
0,65438,Marketing,Sudeste,Mestrado ou Doutorado,F,Outsourcing,1,35,5.0,8,0
1,65141,Logistica,Nordeste,Superior,M,Outro,1,30,5.0,4,0
2,7513,Marketing,Sudeste,Superior,M,Outsourcing,1,34,3.0,7,0
3,2542,Marketing,Norte,Superior,M,Outro,2,39,1.0,10,0
4,48945,Tecnologia,Nordeste,Superior,M,Outro,1,45,3.0,2,0

In [ ]:
# Imports
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.svm import SVR
import pandas as pd

# Parâmetros
mesh_size = .02
margin = 0

# Dataset
df = pd.read_csv('dadosRH_modificado.csv')

# Variáveis
X = df[['idade', 'aval_ano_anterior']]
y = df['promovido']

# Cria o modelo de Machine Learning
modelo = SVR(C=1.)

# Treina o modelo
modelo.fit(X, y)

# Mesh grid para mostrar o resultado do modelo
x_min, x_max = X.sepal_width.min() - margin, X.sepal_width.max() + margin
y_min, y_max = X.sepal_length.min() - margin, X.sepal_length.max() + margin
xrange = np.arange(x_min, x_max, mesh_size)
yrange = np.arange(y_min, y_max, mesh_size)
xx, yy = np.meshgrid(xrange, yrange)

# Previsões com o modelo
pred = modelo.predict(np.c_[xx.ravel(), yy.ravel()])
pred = pred.reshape(xx.shape)

# Gera o plot 3D
fig = px.scatter_3d(df, x = 'idade', y = 'aval_ano_anterior', z = 'promovido')
fig.update_traces(marker = dict(size=5))
fig.add_traces(go.Surface(x = xrange, y = yrange, z = pred, name = '3D promovido'))
fig.show()

# Fim